### ISSUE TITLE
Support rnpm

### ISSUE THREAD

**Issue by lopezjurip** [AlbertBrand/react-native-android-tablayout#10]
Would be possible to automate the installation step with [rnpm](https://github.com/rnpm/rnpm)?

**Comment by AlbertBrand** [comment]
I thought that rnpm doesn't modify the MainActivity class. Then it would still be a 2-step installation. But I might be wrong, haven't tested it out yet.

**Comment by mikewoudenberg** [comment]
If you look at https://github.com/rnpm/rnpm#commands it should be possible in a postlink step.

**Comment by AlbertBrand** [comment]
I just tried out with a freshly inited project using `react-native init example` and after a `npm i --save react-native-android-tablayout` and then `rnpm link react-native-android-tablayout` it it fully linked, including the changes to `MainActivity.java`. I'll update the docs and remove my own installer in favor of rnpm.
