### ISSUE TITLE
ReactNative.createElement is deprecated.

### ISSUE THREAD

**Issue by Hanashi** [AlbertBrand/react-native-android-tablayout#19]
If I use "react-native-android-tablayout", I get this warning:
`Warning: ReactNative.createElement is deprecated. Use React.createElement from the "react" package instead`

**Comment by AlbertBrand** [comment]
Yeah, deprecated since 0.25. I'll update the code soon.

Op vr 20 mei 2016 15:25 schreef Hanashi notifications@github.com:

**Comment by AlbertBrand** [comment]
Done, version 0.3.0 is now RN 0.28+
