### ISSUE TITLE
Support tab backgroundColor

### ISSUE THREAD

**Issue by shukerullah** [AlbertBrand/react-native-android-tablayout#7]
Please provide backgroundColor support to tab

**Comment by AlbertBrand** [comment]
Background color of the entire TabLayout is already supported, just style it using a backgroundColor. If you need separate tab colors per tab, I'm happy to merge PR's :smiley:.

**Comment by ghengeveld** [comment]
+1

**Comment by AlbertBrand** [comment]
Setting the background color of a single tab seems to be quite non-standard, see the [design docs](https://www.google.com/design/spec/components/tabs.html#tabs-content). I'm closing this.

**Comment by wietsevenema** [comment]
+1

**Comment by ghengeveld** [comment]
:disappointed: What about textHighlightColor?
