### ISSUE TITLE
Performance Issue on Android

### ISSUE THREAD

**Issue by shukerullah** [AlbertBrand/react-native-android-tablayout#9]
Tablayout together with ViewPagerAndroid has performance issue. Tablayout response slow when ViewPager is changed, even JS Dev Mode is disabled.

**Comment by AlbertBrand** [comment]
I'm not seeing a perf issue with the [ViewPagerTabLayout](/AlbertBrand/react-native-android-tablayout/blob/master/example/app/ViewPagerTabLayout.js) example. Can you elaborate?

**Comment by shukerullah** [comment]
I disabled JS Dev Mode and it worked well.
